### ISSUE TITLE
Creates settings.json in every project

### ISSUE THREAD

**Issue by onwardmk** [leodevbro/vscode-blockman#133]
Blockman creates a `settings.json` file in every project that has a `.vscode` folder. How do I disable this behavior?

**Comment by leodevbro** [comment]
Please provide, what is the content of the created `settings.json` file? I have never seen Blockman creating such file.

**Comment by onwardmk** [comment]
The content of the file is this:
```json
{
    "workbench.colorCustomizations": {
        "editor.lineHighlightBackground": "#1073cf2d",
        "editor.lineHighlightBorder": "#9fced11f"
    }
}
```

I already added these to my user settings, so I'm not sure why this file is created in every workspace.

**Comment by leodevbro** [comment]
Sorry, I could not reproduce it. I tried manually creating `.vscode` file, also tried to create `[name].code-workspace` file, also tried to clear state of Blockman to trigger the activation events as it would be on a first installation event. But Blockman does not seem to have any deal with `.vscode` folder or inner files of that folder.

Almost 3 years passed since I published Blockman, and I have never seen anyone experiencing this issue. And it seems also logical, because Blockman applies the settings only on the first installation event, never again. Blockman does not change anything on restart, or when you open a new project folder.

**Comment by onwardmk** [comment]
Thank you for taking some time to look into this. I must have a global setting somewhere that I'm unaware of that's doing this. I just assumed it was something in Blockman because I have many other extensions installed, and it started happening after I installed Blockman. The settings in the `settings.json` also only happen to be the ones that are set by Blockman.

**Comment by leodevbro** [comment]
Maybe it would be good if you try to create a new profile in VS Code. With this new profile, you can have only one extension (Blockman), and test it how it will deal with `.vscode` folder. You can switch between the new profile and old default profile any time.

**Comment by onwardmk** [comment]
I created a new profile with only the Blockman extension installed and the `settings.json` file is not generated when I use that profile. I'll try disabling settings in my default profile one-by-one to track down the cause. I appreciate your help!
