### ISSUE TITLE
Idea: Open-ended gradient 

### ISSUE THREAD

**Issue by MHHenriksen** [leodevbro/vscode-blockman#18]
A free idea for you :D

As a design alternative that mitigates the autosizing limitations, having the right side of the boxes borderless and fading out would be interesting to see. Something like this crude mockup:
![image](https://user-images.githubusercontent.com/20283377/121903722-dde39e80-cd28-11eb-9213-e3cc77739e42.png)

Drawback: Midline blocks won't look that good, maybe? 

Edit: As a choice, not a replacement of course ;)

**Comment by LongChampion** [comment]
I like it too. Hope that the author will implement it soon :smile:

**Comment by leodevbro** [comment]
![2021-06-15_11-46-57](https://user-images.githubusercontent.com/54504880/122013706-7b91a900-cdcf-11eb-8582-a91bd44620a9.png)

That's kinda interesting. The problem is that css border cannot have gradient, it can be only solid color, so I removed the borders in the image above.

Maybe I will remake the borders as back-layer divs, so they will be able to support gradients. I guess it will be kinda tradeoff for optimization, because each block rendering is very CPU intensive, the blocks are not just blocks, they are rendered line by line, each line has its div, these divs touch each other so it gives us illusion that its a one whole block. So, remaking borders as additional divs would add more work for CPU.

**Comment by leodevbro** [comment]
Redesigned the borders as divs. Looks quite interesting. maybe I'll implement somehow soon.

![image](https://user-images.githubusercontent.com/54504880/122031090-691f6b80-cddf-11eb-8f95-fdd9e57ea56e.png)

**Comment by leodevbro** [comment]
Before and After.

![2021-06-15_13-48-11](https://user-images.githubusercontent.com/54504880/122032348-9ae50200-cde0-11eb-8dc1-4ea0fdb2d2ad.png)

**Comment by leodevbro** [comment]
The new version (1.3.0) of Blockman now supports gradient for both: borders and backgrounds. You can choose Super gradient color combo preset, or manually set custom gradients.

![2021-11-11_02-23-10](https://user-images.githubusercontent.com/54504880/141206414-edc5e0e9-390d-4cf3-a1eb-68b8f7df40e1.png)

**Comment by MHHenriksen** [comment]
_**Super**_ good work!
