### ISSUE TITLE
Bug: boxes overlap text

### ISSUE THREAD

**Issue by irongollem** [leodevbro/vscode-blockman#37]
I installed the plugin without changing any settings and the blocks are deeper than the text they should contain.

This goes for .ts files. .ejs files look just fine.

![block overlap](https://i.ibb.co/GPNmL91/Screenshot-2021-08-16-at-11-32-49.png)

**Comment by leodevbro** [comment]
Can you provide the code of the entire file? also please provide the settings:
* font family
* font size

**Comment by leodevbro** [comment]
@irongollem, Can you provide these?
* Entire file code
* font size
* font family

**Comment by Jamminroot** [comment]
Not sure if the same problem, but still:

![image](https://user-images.githubusercontent.com/6387654/142737273-7fba463a-d2b5-4ac8-bd1e-88f894a3bbcc.png)

Sample code:
```cpp
void print_arr(const array2<uint8_t> &arr) {
    scope_profiler t("print_arr");
    for (size_t x = 0; x < arr.get_length(0); ++x) {
        for (size_t y = 0; y < arr.get_length(1); ++y) {
            std::cout << std::to_string(arr(x, y)) << " ";
        }
    }
}
```
Border kind of overlaps text for me (especially those double quotes), which makes it harder to read. It'd be great to only enable subtle background tint, with no border at all.

Font is Fira Code, 12

**Comment by leodevbro** [comment]
@Jamminroot, I see that font size is very small in your screenshot, line height seems too short (by pixels), that's why there is not enough pixel-space left for some graphical elements. I suggest to increase font size.

Also if you want to hide borders, you can do it in Blockman settings. Also you can do so many things in Blockman settings. Please play around with it, and ask me any questions if anything seems confusing.
