### ISSUE TITLE
Only rendering half lines

### ISSUE THREAD

**Issue by henry-js** [leodevbro/vscode-blockman#44]
This:
![image](https://user-images.githubusercontent.com/79054685/134415838-1d0f6a78-a743-43a8-a909-dd29d1dc05fd.png)

**Comment by leodevbro** [comment]
What values do you have in these settings?

* Editor: Line Height
* Editor: Mouse Wheel Zoom

![2021-09-23_00-30-47](https://user-images.githubusercontent.com/54504880/134417484-de52bbd2-1f4e-4242-b021-fe604aa8b00f.png)

**Comment by henry-js** [comment]
Ahhh yes my editor.lineHeight was 1.2

**Comment by leodevbro** [comment]
Now, does it look fine when the lineHeight is set to `0`? also looks fine when the lineHeight is set to `1`? Maybe not?

**Comment by henry-js** [comment]
Looks like any value != 0 causes issues

**Comment by leodevbro** [comment]
It worked fine before. There have been some changes in VSCode settings since the latest updates of VSCode.
I figured out the change, so I'll fix it soon, maybe tomorrow.

**Comment by leodevbro** [comment]
I updated Blockman.
Current version is 1.2.9 (2021-09-25).

-   Fixed line height issue (The issue was caused by VSCode update)
-   Added command: press F1 and find 'Blockman Select Focused' (selects the text inside focused block)
-   Added command: press F1 and find 'Blockman Toggle Freeze/Unfreeze Focus'
