### ISSUE TITLE
Remove horizontal lines that are distracting at normal zoom levels

### ISSUE THREAD

**Issue by mikef80** [leodevbro/vscode-blockman#52]
Hi.  Firstly, let me say that this is a great extension! I heard about it when you posted it on Codecademy and have shared with so many people!

When at normal zoom levels, I have an awful lot of horizontal lines generated by Blockman, as shown in the first screen shot:

![image](https://user-images.githubusercontent.com/9698001/141763097-6e8dee8b-9c11-44f2-a247-e8e8a7a5b14a.png)

However, when I zoom out a bit, these disappear, leaving behind just the borders of the blocks.  I can't find an option to make this the default choice for me - is it possible?

![image](https://user-images.githubusercontent.com/9698001/141763306-2348da3e-16b4-40e2-a85f-c076a842b620.png)

Thank you!

**Comment by Ollie-Boyd** [comment]
I just came to ask about the same issue 
![Uploading image.png…]()

**Comment by leodevbro** [comment]
I think it is a VSCode limitation, not a bug of Blockman.
`the editor font zoom is not exposed in any way to the API`, so, it means Blockman cannot detect font zoom level, because VSCode API simply does not give us access to it.

https://github.com/microsoft/vscode/issues/125341#issuecomment-854962933

**Comment by leodevbro** [comment]
Also, I want to ask you, which type of zoom are you mentioning? mouse wheel zoom? or `Window: Zoom Level` ?

**Comment by Ollie-Boyd** [comment]
@leodevbro mine shows these horizontal lines on a fresh install of VS Code at default zoom level. If I ctrl+'-' to zoom out the lines reduce but they are still there. When I scroll the lines jump about

**Comment by Ollie-Boyd** [comment]
Default zoom
![image](https://user-images.githubusercontent.com/50486871/141965602-59f46cfb-8168-4095-bee1-4bb995ce22f9.png)
Zoomed out
![image](https://user-images.githubusercontent.com/50486871/141965762-4842eb87-98c4-4459-a724-cdca9a74f9ce.png)

**Comment by mikef80** [comment]
Mine also shows on default zoom levels.  What I have noticed though is that it's only happening on my home PC (4K monitors set to 150% scale).  Mine behave much as @Ollie-Boyd describes above. However, my work monitors (Full HD at 100% scale) don't show these horizontal lines, no matter how much I zoom in or out. Both systems are using fresh installs and I have tried it with all other add-ons disabled to check for any adverse interaction.

**Comment by abhi-k9** [comment]
Can confirm this issue on default zoom.

Lines appear and disappear on scrolling. There doesn't seem to a specific patter as far as I can tell.

**Comment by leodevbro** [comment]
Have anyone here experienced this issue on a monitor with less than 4K resolution?

**Comment by abhi-k9** [comment]
That would be me.

**Comment by mikef80** [comment]
> That would be me.

What resolution are you using and are you scaling at all?

**Comment by leodevbro** [comment]
![image](https://user-images.githubusercontent.com/54504880/142668566-6f485eeb-e506-41dd-b9fd-df24e94f9759.png)

Well, now I tested on my 1920x1080 monitor with playing around the Windows `scaling` settings. Turns out the block rendering of Blockman extension goes crazy (like in your screenshots) on every percentage setting other than 100%. So, I think the problem is in Windows 10 scaling algorithm or in VSCode scaling algorithm or both. So, I guess Blockman itself is not responsible for this issue at all.

So, maybe we should make a `bug report` in VSCode repo in Github.

**Comment by abhi-k9** [comment]
System display settings:
- Scale: 125% (Recommended)
- Resolution: 1920 x 1200 (Recommended)

VSCode settings:
- Editor Font Size: 18

As @leodevbro  pointed out, issue seems to disappear on 100% scaling.

**Comment by Ollie-Boyd** [comment]
Grrr, everything is so tiny on my 1080p 13" at 100%. Shoukd I make a bug report to vs code? Not sure how to describe the problem
________________________________

**Comment by mikef80** [comment]
I think that’d be good, but I’m not sure how to describe the problem. I’m still pretty new to this and wouldn’t have the first clue how this was built!

**Comment by leodevbro** [comment]
I made a `bug report` just now in the `vscode` repo:
https://github.com/microsoft/vscode/issues/137609

Please `like` it, so it gets better chance to be fixed.

**Comment by leodevbro** [comment]
Very good news: I fixed the mouse wheel zoom behavior of Blockman. The latest version of Blockman is `1.4.5 (2022-01-03)`.

I know your issue is not about mouse wheel zoom, it's about `Window: Zoom Level` (`Ctrl` and `+` / `-`), but I think the fix of mouse wheel zooming will greatly help the `Window: Zoom Level` zooming to have much less artifacts (horizontal lines). Please check it out.

**Comment by mathric** [comment]
Just got into the same problem. Have solved it temporarily using try and error way by adjust the Mouse Wheel Scroll Sensitivity and zoom level in vscode setting. Hope this can help someone before the bug report being addressed.

**Comment by leodevbro** [comment]
@mikef80, @abhi-k9, @rgehrsitz, @Ollie-Boyd, @mathric,
Hi everyone, I want to ask you to update VSCode to the latest version (1.66) and check the issue again. For me, I discovered that somehow this issue (strange horizontal lines) is no longer reproducible in my machine. It seems pretty much fixed. Well, I tried many different ugly zooming settings and the worst scenario I got is one or two rare horizontal lines, so in most cases it seems fixed. So, please check it again and tell me if the situation is changed or not.

**Comment by mikef80** [comment]
Hi @leodevbro,

You're right!  I've just updated to 1.66 on my Mac and it looks like the issue is gone.  Perfect!  Haven't checked on my own PC yet, but my work PC appears to also be fixed!  Great work!

**Comment by rgehrsitz** [comment]
It's working on my 4K Windows display using using VSCode 1.66.  Now I can appreciate what this extension is really supposed to look like.  Excellent!

**Comment by mikef80** [comment]
Yeah, mine's a 4K too - looks bloody great!

**Comment by mathric** [comment]
Yes, it also works on my laptop which is not support 4K
