### ISSUE TITLE
Doesn't render correctly with rust-analyzer 

### ISSUE THREAD

**Issue by emanuellima1** [leodevbro/vscode-blockman#57]
When I use Blockman with rust-analyzer the following happens:

![image](https://user-images.githubusercontent.com/7927924/146106849-c23ee5cb-abb4-45c6-a15a-566c9fa50295.png)

The type hints that rust-analyzer adds to the code make the line go out of it's section. The point is, these type hints are not actual text that is written. It is just rendered on the editor. So is that why it bugs Blockman? Maybe it is related to [this](https://github.com/microsoft/vscode/issues/118994)?

**Comment by leodevbro** [comment]
Yeah, it's not exactly bug of Blockman. It's the limitation of VSCode. It does not give us access to pixel locations of text characters, so Blockman calculates locations by the number of characters. So that's why Blockman disables (at the initial install event) those type hints with this setting:

`editor.inlayHints.enabled": false,`
