### ISSUE TITLE
Suggestion: Korean character support + many other double width characters

### ISSUE THREAD

**Issue by sni-J** [leodevbro/vscode-blockman#72]
I found that Korean comment breaks the box.
There was a related issue and solution about Chinese characters https://github.com/leodevbro/vscode-blockman/issues/11#issuecomment-859994656 and looks like it applied in here: https://github.com/leodevbro/vscode-blockman/blob/d6743e72f335de49ca1ae093c363288797f29163/src/helpers/regex-main.ts#L3
But this regex misses some range of double width characters that unicode provide.
To support only generally used Korean characters, just adding `가-힣`(`\uAC00-\uD7A3`) would be enough, but fyi I'll provide some links related to it.
- https://www.unicode.org/reports/tr11
- https://www.unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt (linked file in unicode report above)

btw, I really appreciate that this extension helps me a lot 👍🏻

**Comment by leodevbro** [comment]
Thanks for the feedback.
I added the regex you provided for generally used Korean characters.
The latest version of Blockman is `v1.5.6` (2022-02-21).

I hope it will work fine.
If any other suggestions, feel free to comment.

**Comment by sni-J** [comment]
🎉   I've tried new version and works perfectly 🎉 

... except its bit wider than expected, but still a lot better than before and for me it's totally enough
![image](https://user-images.githubusercontent.com/38968140/155637845-54de6ebf-65bd-40e7-b22d-e6db465b0374.png)
This looks like double width (full-width) character does not exactly match with `"Z_"` below
https://github.com/leodevbro/vscode-blockman/blob/d10e1544095da88fea37c24b963e278846477f3e/src/utils2.ts#L484-L489

Anyway thanks for support! I hope you get lots of Korean users😄

**Comment by leodevbro** [comment]
Thanks. Well, the reason it is wider, is probably one of these:

1) The Korean characters maybe are not exactly 2 English (Latin) monospace character wide.

2) The Korean characters maybe are 2 Latin monospace character wide, but probably you are using mix of two (or more) fonts (Maybe a mix of English font and Korean font). Two fonts, they may be both monospace, but often times different monospace fonts have different char widths, and so the length of any line cannot be computed precisely, because it is calculated by multiplying number of chars with the px width of one char.

I created a feature request in VSCode github repo to provide extension API to access px locations of any character in any line, so Blockman will be able to calculate block dimensions more precisely.
