### ISSUE TITLE
Incorrect definition of the beginning of blocks

### ISSUE THREAD

**Issue by bimkassir** [leodevbro/vscode-blockman#81]
Today I turned on the extension and faced with the fact that the blocks do not start where they should.
I use:
   "editor.fontFamily": "Verdana",
   "editor.fontSize": 12,
file: .vue (it works the same way in .js).
![Screenshot_1](https://user-images.githubusercontent.com/24460845/173006267
![Screenshot_3](https://user-images.githubusercontent.com/24460845/173006287-224dbade-c8f3-478e-9d7c-8b7a8d4d38f0.png)
![Screenshot_2](https://user-images.githubusercontent.com/24460845/173006276-3002bfd6-7c99-4fa4-8d62-875197584e14.png)
-2a2c4669-e99c-4af1-ba24-043255e5f063.png)

Screen attached. I'll be happy to add any additional information you need.

**Comment by leodevbro** [comment]
Hello, "Verdana" font is not a **monospace** font. In general, it's not a good idea to use non-monospace font in a code editor.

In Blockman page, I have written this instruction:

<p>Please don't use non-monospace font. Use only monospace font like 'Oxygen Mono', '<a href="https://bpgfonts.wordpress.com/2017/12/21/bpg-2017-dejavu-sansmono/">BPG 2017 DejaVu Sans Mono</a>' or other. Block-rendering is based on equal character-frame-widths, because pixel locations of characters <a href="https://github.com/microsoft/vscode/issues/118994">is not accessible</a> through VS Code API.</p>
